# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    documents:
      uri_prefix: /dossier/documents
      upload_destination: '%kernel.project_dir%/public/dossier/documents'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer